### PR TITLE
2to3

### LINKED ISSUE #50: Python 3
Do the right thing...

### PR DESCRIPTION
**Pull request by mnot**
... with associated test cleanup.

Fixes #50.

### CODE REVIEW

**Comment by mnot** [comment]
Digest ordering is still different, which is odd; need to chase that down.

**Comment by mnot** [comment]
OK, I think this is good to go. I've made two changes to make testing deterministic:

* Made ordering of commenters (parenthetically listed) alphabetical, rather than random (they were collected in a Set()).
* Made ordering of issues commented upon by issue number, rather than number of comments (since issues having the same number of comments can change order).

@dontcallmedom PTAL.

**Comment by dontcallmedom** [comment]
this looks great, thank you so much @mnot ! if you don't mind, I'll merge this once I have confirmation I can get the new version properly deployed on our end (hopefully in the next few days).

**Comment by mnot** [comment]
That's great, thanks.

**Comment by mnot** [comment]
Ping? I know things have been busy.

**Comment by dontcallmedom** [comment]
@mnot now merged and deployed, and so far seems to work - thanks again for providing this!

**Comment by mnot** [comment]
Thanks!

**Pull request merged**
