### PR TITLE
Allow config from environment; SMTP SSL and login

### PR DESCRIPTION
**Pull request by mnot**
I'm aiming to run this from GitHub actions and other CI systems, so I need to be able to get config (especially secrets) from the environment, and to use remote SMTP securely.

### CODE REVIEW

**Comment by mnot** [comment]
(I don't think this should effect any existing deployments)

**Comment by dontcallmedom** [comment]
I'm interested to learn more about your github actions deployment when you have a chance :)

**Comment by mnot** [comment]
I'm collecting information about ietf repos using an [ietf.json](https://github.com/mnot/ietf-repo-data#ietf-repository-data-service) file. That repo uses Actions to scrape the GitHub API and commit back to itself.

Then, I use that data for other services. The first is a [weekly issue summary e-mail](https://github.com/mnot/ietf-github-tools), also sent from Actions; this is next ;)

I think those repos contain everything that's relevant; tell me if you have any questions, and I'll ping you once I get this up and running :)

**Comment by mnot** [comment]
See https://github.com/ietf-github-services/activity-summary 

Not live yet, still testing, but it seems to work.

**Pull request merged**
